[workspace]
members = ["rust-wallet-fingerprint"]
resolver = "2"

[workspace.package]
name = "wallet-fingerprint"
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
bitcoin = { version = "0.32.5", features = ["rand"] }
hex = "0.4.3"
